Milestone 2: Portfolio Setup on Mobile version
smas0900/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2022-04-23 21:44 UTC by smas0900

In this milestone we:

- Added Html &CSS file.
- Added Logos..
- Merge the project from previous Project.

2022-04-23 22:52 UTC, AnselemOdims requested changes
### Hi @smas0900 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-23 22:52 UTC, AnselemOdims commented on index.html
> +            <button class ="card_see" type="button">See Project</button>
- [ ] Good job using a `button` tag for this but please kindly ensure that the style for its different states(hover, pressed and inactive) are taken care of.

![image](https://user-images.githubusercontent.com/43995830/164948400-1339280c-0159-4e34-81d8-1c297991bc91.png)

2022-04-23 22:52 UTC, AnselemOdims commented on index.html
> +                <li class="box"><button type="button">html</button></li>
- [ ] Please kindly make sure that the same font used in the original design is also used.
- [ ] Please ensure that the cards have a `border-radius` as it is in the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/164948468-cb13132c-46d9-4313-83de-57e41c053043.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/164948500-d154b6ab-cd32-4d47-b32e-57f87866ac56.png)

2022-04-23 22:52 UTC, AnselemOdims commented on index.html
> +       <button class="btn" type="button">Get my resume</button>
- [ ] Please kindly make sure the same font used in the original design is used here also
- [ ] Please ensure that there is enough padded space at the top, just before the `About Myself` heading
- [ ] Please ensure that the button style reflects the different states(hover, pressed and inactive)

### Your Design
![image](https://user-images.githubusercontent.com/43995830/164948574-44976135-ac89-4570-89a8-095d2697f673.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/164948586-9f1f4a1f-b9f4-4caf-a1ee-b2ef7b849315.png)

2022-04-24 02:36 UTC, omar-labana commented
# **Approved ✔️**

Hi @ ,

Congratulations on completing this project! 👏🏼 🎉

- [ ] _[OPTIONAL]_ Please consider using [responsively](https://responsively.app/) when developing your app, some styling edge cases are not correctly maintained on very small screen sizes ~320 px.
You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-24 02:40 UTC, merged

2022-08-18 21:29 UTC, BertrandConxy reviewed
Hi @smas0900 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, whose PR has already been merged a long ago

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-18 23:18 UTC, smas0900 commented
I did this project before now I am repeating the module
So what should i do?

2022-08-19 06:00 UTC, BertrandConxy commented
oh.. I think when you have repeated the module,  the solo projects which have been approved already,  are supposed to be approved again.
Please request another review and inform the user about your case

2022-08-19 10:08 UTC, MaganaAsiati reviewed
# Hi @smas0900 
## Invalid Code Review Request :negative_squared_cross_mark:
made a great effort in this project, unfortunately, I cannot proceed to review your code.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>


- [ ] You have submitted a project  which has been already approved, kindly make sure you submit the right  link and make your pull request more descriptive 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
Cheers and Happy coding!👏👏👏
--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-08-19 14:43 UTC, smas0900 commented
@MaganaAsiati can you explain what should i do now did u read @BertrandConxy comments?